PADROES_BERT_PT = {
    'HIPERONIMO_4_2_100_50_concreto':       ['o [MASK] é um <r>', 'o [MASK] é uma <r>', 'a [MASK] é um <r>', 'a [MASK] é uma <r>',
                                             'o [MASK] é um tipo de <r>', 'a [MASK] é um tipo de <r>',
                                             'um [MASK] ou outro <r>', 'um [MASK] ou outra <r>', 'uma [MASK] ou outro <r>', 'uma [MASK] ou outra <r>',
                                             'o [MASK] é uma espécie de <r>', 'a [MASK] é uma espécie de <r>',
                                             'o [MASK] é uma classe de <r>', 'a [MASK] é uma classe de <r>',
                                             '<r>, como o [MASK]', '<r>, como a [MASK]',
                                             'se [MASK] é hipónimo de <r>', 'se <r> é hiperónimo de [MASK]'],
    'HIPERONIMO_4_2_100_50_abstrato':       ['o [MASK] é um <r>', 'o [MASK] é uma <r>', 'a [MASK] é um <r>', 'a [MASK] é uma <r>',
                                             'o [MASK] é um tipo de <r>', 'a [MASK] é um tipo de <r>',
                                             'um [MASK] ou outro <r>', 'um [MASK] ou outra <r>', 'uma [MASK] ou outro <r>', 'uma [MASK] ou outra <r>',
                                             'o [MASK] é uma espécie de <r>', 'a [MASK] é uma espécie de <r>',
                                             'o [MASK] é uma classe de <r>', 'a [MASK] é uma classe de <r>',
                                             '<r>, como o [MASK]', '<r>, como a [MASK]',
                                             'se [MASK] é hipónimo de <r>', 'se <r> é hiperónimo de [MASK]'],
    'HIPERONIMO_inv_4_2_100_50_concreto':   ['<r> é um [MASK]', '<r> é uma [MASK]',
                                             '<r> é um tipo de [MASK]',
                                             '<r> ou outro [MASK]', '<r> ou outra [MASK]',
                                             '<r> é uma espécie de [MASK]',
                                             '<r> é uma classe de [MASK]',
                                             'um [MASK], como <r>', 'uma [MASK], como <r>',
                                             '<r> é hipónimo de [MASK]', 'se [MASK] é hiperónimo de <r>'],
    'HIPERONIMO_inv_4_2_100_50_abstrato':   ['<r> é um [MASK]', '<r> é uma [MASK]',
                                             '<r> é um tipo de [MASK]',
                                             '<r> ou outro [MASK]', '<r> ou outra [MASK]',
                                             '<r> é uma espécie de [MASK]',
                                             '<r> é uma classe de [MASK]',
                                             '<r> é hipónimo de [MASK]', 'se [MASK] é hiperónimo de <r>'],
    'HIPERONIMO_ACCAO_3_2_100_50':      ['e se [MASK] é uma forma de <r>', 'e se [MASK] é um modo de <r>', 'e se [MASK] é uma maneira de <r>',
                                         'como [MASK] e outras formas de <r>', 'como [MASK] e outras maneiras de <r>', 'como [MASK] e outros modos de <r>',
                                         'como [MASK] ou outras formas de <r>', 'como [MASK] ou outras maneiras de <r>', 'como [MASK] ou outros modos de <r>',
                                         'e se [MASK] é como <r>', 'vou <r> a [MASK]', 'para <r> a [MASK]'], #=manner?
    'HIPERONIMO_ACCAO_inv_3_2_100_50':  ['<r> é uma forma de [MASK]', '<r> é um modo de [MASK]', '<r> é uma maneira de [MASK]',
                                         'como <r> e outras formas de [MASK]', 'como <r> e outras maneiras de [MASK]', 'como <r> e outros modos de [MASK]',
                                         'como <r> ou outras formas de [MASK]', 'como <r> ou outras maneiras de [MASK]', 'como <r> ou outros modos de [MASK]',
                                         '<r> é como [MASK], mas', 'vou [MASK] a <r>', 'para [MASK] a <r>'], #'[MASK] a <r>',

    #plurais: 'um [MASK] inclui <r>', 'uma [MASK] inclui <r>', 'um [MASK] contém <r>', 'uma [MASK] contém <r>',
    #plurais: 'um <r> inclui [MASK]', 'uma <r> inclui [MASK]', 'um <r> contém [MASK]', 'uma <r> contém [MASK]',
    'PARTE_2_2_100_50':     ['o <r> do [MASK].', 'o <r> da [MASK].', 'a <r> do [MASK].', 'a <r> da [MASK].',
                             'um [MASK] tem <r>', 'uma [MASK] tem <r>', 'um [MASK] possui <r>', 'uma [MASK] possui <r>',
                             'o [MASK] tem <r>', 'a [MASK] tem <r>', 'o [MASK] possui <r>', 'a [MASK] possui <r>',
                             '<r> faz parte de [MASK].', '<r> faz parte da [MASK].', '<r> faz parte da [MASK].',
                             '<r> é uma parte de [MASK].', '<r> é uma parte do [MASK].', '<r> é uma parte da [MASK].'],
    'PARTE_inv_2_2_100_50': ['o [MASK] do <r>', 'o [MASK] da <r>', 'a [MASK] do <r>', 'a [MASK] da <r>',
                             '<r> tem um [MASK].', '<r> tem uma [MASK].',
                             '<r> possui um [MASK].', '<r> possui uma [MASK].',
                             'o <r> tem um [MASK].', 'o <r> tem uma [MASK].', 'a <r> tem um [MASK].', 'a <r> tem uma [MASK].',
                             'o <r> possui um [MASK].', 'o <r> possui uma [MASK].', 'a <r> possui um [MASK].', 'a <r> possui uma [MASK].',
                             'um [MASK] faz parte de <r>', 'uma [MASK] faz parte de <r>', 'um [MASK] é uma parte de <r>', 'uma [MASK] é uma parte de <r>',
                             'o [MASK] faz parte de <r>', 'a [MASK] faz parte de <r>', 'o [MASK] é uma parte de <r>', 'a [MASK] é uma parte de <r>'],
    'FINALIDADE_3_2_100_50':        ['um [MASK] serve para <r>', 'uma [MASK] serve para <r>', #'o [MASK] serve para <r>', 'a [MASK] serve para <r>',
                                     'o [MASK] para <r>', 'a [MASK] para <r>', #'um [MASK] para <r>', 'uma [MASK] para <r>',
                                     #'o [MASK] é necessário para <r>', 'a [MASK] é necessária para <r>',
                                     'preciso de um [MASK] para <r>', 'preciso de uma [MASK] para <r>',
                                     'um [MASK] é usado para <r>', 'uma [MASK] é usada para <r>', #'o [MASK] é usado para <r>', 'a [MASK] é usada para <r>',
                                     'a <r> com um [MASK]', 'a <r> com uma [MASK]'],
    'FINALIDADE_inv_3_2_100_50':    ['um <r> serve para [MASK]', 'uma <r> serve para [MASK]',
                                     'um <r> para [MASK]', 'uma <r> para [MASK]',
                                     'o <r> é necessário para [MASK].', 'a <r> é necessária para [MASK].',
                                     'um <r> é usado para [MASK]', 'uma <r> é usada para [MASK]',
                                     'a [MASK] com um <r>', 'a [MASK] com uma <r>'],

    'ANTONIMO_ADJ_5_2_100_50': ['<r> é o contrário de [MASK]', '<r> é antónimo de [MASK]', 'ou <r> ou [MASK]',
                                'porque [MASK] é o contrário de <r>', 'porque [MASK] é antónimo de <r>', 'ou [MASK] ou <r>',
                                'estar [MASK] é o contrário de estar <r>', 'ser [MASK] é o contrário de ser <r>',
                                'estar <r> é o contrário de estar [MASK]', 'ser <r> é o contrário de ser [MASK]'],
    'SINONIMO_N_8_2_100_50':    ['<r> é o mesmo que [MASK]', '<r> é sinónimo de [MASK]', '<r> é igual a [MASK]', '<r> é equivalente a [MASK]',
                                 '<r> é a mesma coisa que [MASK]',],
                                 #evitar quando começa por [MASK]: '[MASK] é o mesmo que <r>', '[MASK] é sinónimo de <r>', '[MASK] é igual a <r>', '[MASK] é igual a <r>'],
    'SINONIMO_V_7_2_100_50':    ['<r> é o mesmo que [MASK]', '<r> é sinónimo de [MASK]', '<r> é igual a [MASK]', '<r> é equivalente a [MASK]',
                                 '<r> é a mesma coisa que [MASK]',],
                                 #evitar quando começa por [MASK]: '[MASK] é o mesmo que <r>', '[MASK] é sinónimo de <r>', '[MASK] é igual a <r>', '[MASK] é igual a <r>'],
    'SINONIMO_ADJ_7_2_100_50':  ['<r> é o mesmo que [MASK]', '<r> é sinónimo de [MASK]', '<r> é igual a [MASK]', '<r> é equivalente a [MASK]',
                                 '<r> é a mesma coisa que [MASK]',
                                 'ser <r> é o mesmo que ser [MASK].', 'estar <r> é o mesmo que estar [MASK].']
                                 #evitar quando começa por [MASK]: '[MASK] é o mesmo que <r>', '[MASK] é sinónimo de <r>', '[MASK] é igual a <r>', '[MASK] é equivalente a <r>'],
}
